### PR TITLE
Made WiFi SSID, hostname and MQTT server dynamic

### PR DESCRIPTION
**Pull request by WickedDurkie**
Hi absalom-muc,

First of all, thanks for your project!

I updated your original project so that you can determine the WiFi SSID, host name and MQTT server when the ESP starts for the first time. For that, you have to connect your WiFi to the ESP_XXXXX accespoint and access 192.168.4.1.

The changes make use of the WifiManager and the latestArduinoJson library.

If you like it, you can merge it, otherwise i will host the changes myself.

### CODE REVIEW

**Comment by absalom-muc** [comment]
Hello WickedDurkie,

Thank you very much for your contribution.

I would prefer to leave the update in your repository. Background of my request is, that I plan midterm to test Tasmota or a similar environment for MHI-AC-Ctrl and I don't want to maintain too many options. If you don't mind, I would add a link [here](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#integration-examples).

**Comment by WickedDurkie** [comment]
Hi absalom-muc,

No problem. I merged the updated branch into 'my' master repo.

**Comment by WorlockM** [comment]
@WickedDurkie i tried your project. But it didn't work for me. I can connect to it via Wifi and configure it. It also connects to my Wifi network after that. But it doesn't seem to send or receive any MQTT commands when I look into my MQTT explorer. I don't have this problem when using absalom-muc his version...

**Comment by WickedDurkie** [comment]
I'll try to take a look next week.

**Comment by WorlockM** [comment]
> I'll try to take a look next week.

Great, let me know if I can do any testing for you.

**Comment by WickedDurkie** [comment]
Hi WorlockM,

Another question. Did you use PubSubClient 2.7 instead of 2.8? There seems
to be a problem in 2.8

**Comment by WickedDurkie** [comment]
Hi WorlockM,

I tested my airco ESP today and its working like it should. It outputs the
mqtt topics under the root topic that is named as the configured host name.

Can you debug and see where it fails?

**Comment by WorlockM** [comment]
Sorry for missing your previous post. I moved to another house 2 weeks ago but, so at this moment I don't have my WiFi modules installed. But I do have new MHI airco's so I will be able to, but that will be in a couple of weeks. I will get back to you when I can!

**Pull request closed without merging**
