### PR TITLE
Fix the pins are not match definition

### PR DESCRIPTION
**Pull request by metarutaiga**
Hello

I found the pins is used SCK not SCK_PIN.
And I added it to supported for my ESP-01S board.

### CODE REVIEW

**Comment by absalom-muc** [comment]
Thanks for your input!

I absolutely agree that always SCK_PIN instead of SCK should be used.

But for two reasons I have concerns related to the adaptions for the ESP01:
1. The existing mapping of the pins is based on the provided MHI-AC-Ctrl PCB layout. And since there is no MHI-AC-Ctrl PCB layout for ESP01 available, the user is free to decide which ESP01 pins are connected to SCK, MOSI, MISO. That means finally the user has to adapt 
**one** #define for selecting ESP01 + worst case  **three** #defines for the selection of his pin mapping if he uses another mapping than you (your approach)
or 
**three** #defines for the selection of his pin mapping.  (current approach)
I believe that this justifies no additional configuration options.
2. Is there a specific reason that you use functions with the pins as parameters? Seems to be easier adding _#include "MHI-AC-Ctrl-core.h"_ to support.h (but so far not tested in detail)

btw: Maybe separate your pull requests in future (especially Fix power on randomly). As far as I know either all or none of them can be merged. A more atomic approach seems to be better.

**Comment by metarutaiga** [comment]
> Thanks for your input!
> 
> I absolutely agree that always SCK_PIN instead of SCK should be used.
> 
> But for two reasons I have concerns related to the adaptions for the ESP01:
> 
> 1. The existing mapping of the pins is based on the provided MHI-AC-Ctrl PCB layout. And since there is no MHI-AC-Ctrl PCB layout for ESP01 available, the user is free to decide which ESP01 pins are connected to SCK, MOSI, MISO. That means finally the user has to adapt
>    **one** #define for selecting ESP01 + worst case  **three** #defines for the selection of his pin mapping if he uses another mapping than you (your approach)
>    or
>    **three** #defines for the selection of his pin mapping.  (current approach)
>    I believe that this justifies no additional configuration options.
Ok, I will remove it.

> 2. Is there a specific reason that you use functions with the pins as parameters? Seems to be easier adding _#include "MHI-AC-Ctrl-core.h"_ to support.h (but so far not tested in detail)
> 
I think the support.h without including MHI-AC-Ctrl-core.h may be clearly and less dependency.

> btw: Maybe separate your pull requests in future (especially Fix power on randomly). As far as I know either all or none of them can be merged. A more atomic approach seems to be better.

**Comment by metarutaiga** [comment]
> **Fix power on randomly:**
> line 49: What is the benefit of having the pull-up for SCK? Do you have measurement results?
> 
SCK is sometime 3600 ~ 3592 randomly with INPUT only.
And I see the older version is INPUT_PULLUP. 

> line 120-122: It doesn't support fixing the power on/off problem, but I agree that it should be added to show clearly the initialization.
Yes, I tried it first time, but it still happened.

**Comment by absalom-muc** [comment]
> 
> 
> > **Fix power on randomly:**
> > line 49: What is the benefit of having the pull-up for SCK? Do you have measurement results?
> 
> SCK is sometime 3600 ~ 3592 randomly with INPUT only.
> And I see the older version is INPUT_PULLUP.
> 
> > line 120-122: It doesn't support fixing the power on/off problem, but I agree that it should be added to show clearly the initialization.
> 
> Yes, I tried it first time, but it still happened.

Does that mean that you have the same problem as coyote1 described in this [issue](https://github.com/absalom-muc/MHI-AC-Ctrl/issues/18#issuecomment-643739863)? Which AC model do you have?

**Comment by metarutaiga** [comment]
> > > **Fix power on randomly:**
> > > line 49: What is the benefit of having the pull-up for SCK? Do you have measurement results?
> > 
> > 
> > SCK is sometime 3600 ~ 3592 randomly with INPUT only.
> > And I see the older version is INPUT_PULLUP.
> > > line 120-122: It doesn't support fixing the power on/off problem, but I agree that it should be added to show clearly the initialization.
> > 
> > 
> > Yes, I tried it first time, but it still happened.
> 
> Does that mean that you have the same problem as coyote1 described in this [issue](https://github.com/absalom-muc/MHI-AC-Ctrl/issues/18#issuecomment-643739863)? Which AC model do you have?

SRK 35 ZSX

Yes, it seems the same problem.

**Comment by absalom-muc** [comment]
> 
> 
> > **Fix power on randomly:**
> > line 49: What is the benefit of having the pull-up for SCK? Do you have measurement results?
> 
> SCK is sometime 3600 ~ 3592 randomly with INPUT only.
> And I see the older version is INPUT_PULLUP.
> 
 I haven't seen fluctuating values ​​are related to an unstable SCK. Have you made many tests? Then I would test it again, too.

>>Is there a specific reason that you use functions with the pins as parameters? Seems to be easier adding #include "MHI-AC-Ctrl-core.h" to support.h (but so far not tested in detail)

>I think the support.h without including MHI-AC-Ctrl-core.h may be clearly and less dependency.

To be honest, I don't like both solutions 100%. What do you think about another approach, when I shift `void MeasureFrequency()` from support.cpp to MHI-AC-Ctrl-core.cpp? This would have the advantage that all low-level SPI-related program parts are in one place, and the `#define` of the pins would be more meaningful again. In addition, there would no `#include "MHI-AC-Ctrl-core.h"` in support.h.

**Comment by metarutaiga** [comment]
Sorry, I close it because my family dropped the board...

**Pull request closed without merging**
