### PR TITLE
Clean PCB

### PR DESCRIPTION
**Pull request by CyberLine**
After Successfully done with this project, i was little bit confused about all the unused holes on the PCB, so i decided to rearange and cleanup the PCB for "Enduser" usage. I removed the second connectorbar and the jumper and also optimized some conductor tracks and GND holes. As this is version 1.1, i will prepare the board wiring diagram for additional Ds18b20 and the resistor in v1.2

### CODE REVIEW

**Comment by CyberLine** [comment]
Finally i added support for DSS18x20 on board with Version 1.2

**Comment by absalom-muc** [comment]
Thank you very much for your contribution CyberLine. Before using the new layout, I suggest some topics for discussion:
1. The DRC of [v1.2](https://github.com/absalom-muc/MHI-AC-Ctrl/pull/46/commits/e0805c5ce242e14f286cccab71f7c12580587a13) shows some errors mainly related clearance/overlap of the DS18B20
grafik
2. I suggest we replace the JST_B5B-PH_Header (2mm pitch) because it is challenging to buy or make an according connector cable.  E.g. it could be easier to use the same connector as we have inside AC (JST XH series). As far as I know there are assembled connector cables available from different sources (but I have to re-check it). What do you think?
3. In context of the previous topic the swap of SCL/MOSI should be resolved
grafik
4. Some users had trouble to buy the DC/DC converter. Maybe we could consider an option with a 7805. There are many sources for the 7805 and it is cheap. But I haven't checked so far the power dissipation and the thermal impact.

I'm looking forward your feedback!

**Comment by CyberLine** [comment]
Hey @absalom-muc .

1) i have removed the Airwire. I will look for another library containing a DS18x20 because in the one i used, there is indeed no way to change the clearance or overlay.

2) Same problem: i will look into another library because eagle does not bring another connector. Thats why i used the Testpads on my PCB Boards to connect the cables.

3) i have swapped the pins in latest commit.

4) For germany, you can buy them at Conrad Electronics. Maybe for the Future its possible to provide multiple boards for different types of DC/DC converters and / or temp sensors.

5) see 4.

Eventually, its an option to sell pre-loaded PCB boards to people interested in the project but not firm with soldering or ordering PCB itself ? For example i ordered the PCB at multi-circuit-boards.eu in a batch of 5 PCB, but i did only need 3, so i left over 2 boards.

**Comment by absalom-muc** [comment]
> 
> 
> Hey @absalom-muc .
> 
>     1. i have removed the Airwire. I will look for another library containing a DS18x20 because in the one i used, there is indeed no way to change the clearance or overlapping.
Thank you @CyberLine 

>     2. Same problem: i will look into another library because eagle does not bring another connector. Thats why i used the Testpads on my PCB Boards to connect the cables.
The external temperature sensor shouldn't be soldered directly on the PCB because then it would measure the heating of the PCB and not the environment temperature. Better is to plan a 3-pin-connector with 100mil pitch. There you could connect with a cable a DS18B20 or a DHT22.

>     3. i have swapped the pins in latest commit.
Thank you. Please also adapt the labeling. Additionally I suggest you give names to the nets.
 
>     4. For germany, you can buy them at Conrad Electronics. Maybe for the Future its possible to provide multiple boards for different types of DC/DC converters and / or temp sensors.
Also Reichelt sells the DC/DC converter. But the price is >5€ and I'm not sure that the price is appropriate for this application. I plan to try it with the 7805 in the next weeks.
But we should try to address all improvements with one PCB. I would like to prevent supporting different PCBs in future. (btw: I just checked: The DHT22 uses also a 3-pin-interface with a pull-up between data and Vcc. So the connector planned for the DS18B20 is most probably reusable for the DHT22) 
>     5. see 4.
Since we can't support all possible temperature sensors I would still prefer the pad grid.

> Eventually, its an option to sell pre-loaded PCB boards to people interested in the project but not firm with soldering or ordering PCB itself ? For example i ordered the PCB at multi-circuit-boards.eu in a batch of 5 PCB, but i did only need 3, so i left over 2 boards.

I don't plan to sell (pre-loaded) PCBs. But I've no problem when you sell the PCBs.

**Comment by absalom-muc** [comment]
One addtional comment related to the AC connector: I searched for assembled 1:1 JST-XH 5 pin cables and found cables with male/female connector e.g 
[ebay](https://www.ebay.de/itm/JST-XH-2-3-4-5-oder-6-Pin-Stecker-Buchse-Kabel-Kupplung-JST-XH/173756605105?hash=item2874b362b1:g:V9gAAOSwNRJcgnw0)
[ebay](https://www.ebay.de/itm/1-10-St-1S-2S-3S-4S-5S-6S-Balancer-Silikon-Kabel-JST-XH-Lipo-20cm-Verlangerung/193646099023?hash=item2d1634fa4f:g:GEUAAOSwqY5fT3kN)
[amazon](https://www.amazon.de/5Pin-Kabel-Buchse-2-54mm-20cm/dp/B07877Y42C/ref=sr_1_15?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=X7FKGNM99J3M&dchild=1&keywords=jst+xh+5+pin&qid=1599926653&sprefix=jst+xh+5%2Caps%2C168&sr=8-15)
[amazon](https://www.amazon.de/Sanwa-Joystick-Encoder-Mayflash-F300-Joystick-Weiblich/dp/B07BK12QBG/ref=sr_1_26?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=X7FKGNM99J3M&dchild=1&keywords=jst+xh+5+pin&qid=1599926653&sprefix=jst+xh+5%2Caps%2C168&sr=8-26)
[aliexpress](https://www.aliexpress.com/item/4001333727614.html?spm=a2g0o.productlist.0.0.79a96a52SqDWLY&s=p&ad_pvid=202009120908054015645216113960005026141_2&algo_pvid=bb3a40fd-5f20-425c-8a99-f23d2734ee48&algo_expid=bb3a40fd-5f20-425c-8a99-f23d2734ee48-1&btsid=0b0a0ac215999268850374918e7257&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)
The availability seems to be ok. So I believe a JST-XH-5Pin-Male connector would be a good choice.

**Comment by CyberLine** [comment]
Just one comment about the DC/DC Pricing: the Original WIFI Adapter for one! MHI Indoor Unit is between 100 and 140€, so i think 5 to 10€ for the Part is fine. I Paid in total 23€ on Materials for one Unit.

**Comment by CyberLine** [comment]
I also added the following cable directly to the Indoor Unit Board:
[amazon](https://www.amazon.de/gp/product/B07NCPFRFR/)

so i can maintain the complete thing much easier as i only have to remove the lower rear panel.

**Comment by damienmorrissey** [comment]
Same. That was a suggestion from the previous project and it is helpful.

**Comment by asonkel** [comment]
just one comment... I found out that all pads of the temp sensor have connection to each other. There is no space between.

**Comment by CyberLine** [comment]
> just one comment... I found out that all pads of the temp sensor have connection to each other. There is no space between.
> 
> 

Yeah. I know. I will update the PR when I have some time again.

**Comment by DYLaKo** [comment]
> > just one comment... I found out that all pads of the temp sensor have connection to each other. There is no space between.
> > 
> 
> Yeah. I know. I will update the PR when I have some time again.

The new design is not yet committed, am I right?

**Comment by absalom-muc** [comment]
You are right it is not committed. But I created already another PCB layout. I'm waiting for the sample PCBs and expect to publish the new version in February.

**Comment by damienmorrissey** [comment]
If it works out I'd be happy to buy up to 5 PCBs if that will make it
cheaper for you.

**Comment by DYLaKo** [comment]
Count me in for 2 PCB's as well if you are able to ship to Holland. ;-)

**Comment by CyberLine** [comment]
While i also need to resolder my existing PCB's, i will also use the new layout provided. I can order them at a price between 5 and 10 € per unit i think.

**Comment by deku-m** [comment]
> 
> 
> While i also need to resolder my existing PCB's, i will also use the new layout provided. I can order them at a price between 5 and 10 € per unit i think.

Where do you order them and is this with cns connector?

**Comment by deku-m** [comment]
COunt me in for 2 also if its fully completed :)

**Comment by absalom-muc** [comment]
Just uploaded a new PCB layout, so topic closed here

**Pull request closed without merging**
