### PR TITLE
DRAFT: kicad: Move connector to the bottom of the PCB

### PR DESCRIPTION
**Pull request by oliv3r**
This changes the appearance of the connector only! The pin-out remains identical, the gerbers, identical. Only the location of the connector moved, which causes the silkscreen to change and the 3D render.

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

### CODE REVIEW

**Comment by oliv3r** [comment]
paused until I can design a JST header in 3D :)

**Comment by absalom-muc** [comment]
Since there seems to be no progress, closed.
But feel free to re-open, once you can design a JST header in 3D

**Comment by oliv3r** [comment]
yeah sorry; will reopen once I model the connector ;)

**Comment by oliv3r** [comment]
See #155 instead of re-opening this one :)

**Pull request closed without merging**
